name: Deploy to andydelgado.dev

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npm run build
        
      - name: Deploy
        run: |
          rm -rf /home/ubuntu/serverSetup/andydelgado.dev/*
          cp -r dist/* /home/ubuntu/serverSetup/andydelgado.dev/
          cd /home/ubuntu/serverSetup/andydelgado.dev
          pm2 restart all --update-env